const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
const state = { model: localStorage.getItem('agy-model') || 'gemini-3.8-flash-medium', theme: localStorage.getItem('agy-theme') || 'dark', history: JSON.parse(localStorage.getItem('agy-history') || '[]'), busy: false };
const models = [{name:'Nemotron Ultra',id:'gemini-3.8-flash-medium',backend:'nvidia/nemotron-3-ultra-550b-a55b',context:'128k',note:'High-context reasoning'},{name:'Nemotron Super',id:'gemini-3.7-flash-medium',backend:'nvidia/nemotron-3-super-120b-a12b',context:'128k',note:'Fast primary'},{name:'Llama Vision',id:'gemini-3.6-flash-medium',backend:'meta/llama-3.2-11b-vision-instruct',context:'128k',note:'Stable vision fallback'},{name:'DeepSeek',id:'gemini-3.1-pro-preview',backend:'deepseek-ai/deepseek-v4.1-flash',context:'128k',note:'Accurate general fallback'}];
function setTheme(t){state.theme=t;document.body.classList.toggle('light',t==='light');localStorage.setItem('agy-theme',t)}
function setModel(id){state.model=id;localStorage.setItem('agy-model',id);$('#modelSelect').value=id;$('#modelText').textContent=models.find(x=>x.id===id)?.name||id;renderModels()}
function renderModels(){$('#modelGrid').innerHTML=models.map(m=>`<article class="model-card ${m.id===state.model?'active':''}"><span class="eyebrow">${m.context} CONTEXT</span><h3>${m.name}</h3><p>${m.backend}<br>${m.note}</p><button class="ghost-btn" data-model="${m.id}">${m.id===state.model?'Selected':'Use model'}</button></article>`).join('');$$('[data-model]').forEach(b=>b.onclick=()=>setModel(b.dataset.model))}
function saveHistory(){localStorage.setItem('agy-history',JSON.stringify(state.history.slice(-80)))}
function addMessage(role,text,model=''){const wrap=document.createElement('div');wrap.className=`message ${role}`;wrap.innerHTML=`<div class="message-meta">${role==='user'?'YOU':model||'ASSISTANT'}</div><div class="message-body"></div>`;wrap.querySelector('.message-body').textContent=text;$('#messages').append(wrap);$('#messages').scrollTop=$('#messages').scrollHeight;return wrap}
function extractCode(text){const match=text.match(/```(?:javascript|js|typescript|ts|python)?\n([\s\S]*?)```/i);if(match){$('#codeView').innerHTML='';const code=document.createElement('code');code.textContent=match[1];$('#codeView').append(code);$('#changedLines').textContent=match[1].split('\n').length;return true}return false}
async function send(){if(state.busy)return;const input=$('#input'),text=input.value.trim();if(!text)return;input.value='';input.style.height='auto';$('.welcome')?.remove();addMessage('user',text);state.history.push({role:'user',text,model:state.model});saveHistory();const answer=addMessage('assistant','',models.find(x=>x.id===state.model)?.name);answer.querySelector('.message-body').textContent='';state.busy=true;$('#sendBtn').textContent='◌';const started=performance.now();let full='';try{const res=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:state.model,contents:state.history.map(x=>({role:x.role==='assistant'?'model':'user',parts:[{text:x.text}]})),generationConfig:{maxOutputTokens:4096}})});if(!res.ok)throw new Error(`Router returned HTTP ${res.status}`);const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop();for(const event of events){for(const line of event.split('\n')){if(!line.startsWith('data:'))continue;try{const data=JSON.parse(line.slice(5).trim());const t=data.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';full+=t;answer.querySelector('.message-body').textContent=full}catch{}}}}$('#latency').textContent=`${((performance.now()-started)/1000).toFixed(1)}s`;if(full){state.history.push({role:'assistant',text:full,model:state.model});saveHistory();extractCode(full)}}catch(err){answer.querySelector('.message-body').textContent=`Request failed: ${err.message}`;$('#logView').textContent+=`\n${new Date().toISOString()}  ${err.message}`}finally{state.busy=false;$('#sendBtn').textContent='➤'}}
function navigate(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`${view}View`));$$('.rail-btn[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}
$$('.rail-btn[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#newChatRail').onclick=()=>{state.history=[];saveHistory();$('#messages').innerHTML='<div class="welcome"><div class="orb"></div><span class="eyebrow">READY TO BUILD</span><h2>What are we creating<br>with <em>intelligence</em> today?</h2><p>Ask anything. Your workspace will unfold as we go.</p></div>';$('#chatTitle').textContent='New conversation'};$('#sendBtn').onclick=send;$('#input').addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,130)+'px'});$('#input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$$('.suggestions button').forEach(b=>b.onclick=()=>{$('#input').value=b.textContent;$('#input').focus()});$('#modelSelect').onchange=e=>setModel(e.target.value);$('#themeBtn').onclick=()=>setTheme(state.theme==='dark'?'light':'dark');$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#saveSettings').onclick=()=>{setTheme($('#themeSelect').value);setModel($('#defaultModel').value);document.body.style.fontSize=$('#fontSize').value+'px';$('#settingsDialog').close()};$('#themeSelect').value=state.theme;$('#defaultModel').value=state.model;setTheme(state.theme);setModel(state.model);renderModels();
